# Generated by Django 4.2.11 on 2024-09-07 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "friends",
            "0004_post_customuser_bio_userfollow_postcomment_post_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="userfollow",
            name="follows",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userfollow",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userfollow",
            unique_together={("user", "follows")},
        ),
    ]
